## PACOTES ##

In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import json
import warnings

from pathlib import Path
from scipy.stats import chi2
from IPython.display import display

In [ ]:

BASE_PATH = Path("thoracic_surgery_base_modelo_statsmodels.csv")
OUTPUT_DIR = Path("outputs")

CAMINHO_MODELO_COMPLETO = OUTPUT_DIR / "modelo_completo.pkl"
CAMINHO_VARIAVEIS_MODELO = OUTPUT_DIR / "variaveis_modelo.json"

CAMINHO_MODELO_FINAL = OUTPUT_DIR / "modelo_final.pkl"
CAMINHO_VARIAVEIS_FINAIS = OUTPUT_DIR / "variaveis_finais.json"
CAMINHO_HISTORICO_SELECAO = OUTPUT_DIR / "historico_selecao.csv"

VAR_RESPOSTA = "obito_1_ano"

ALPHA = 0.05

In [ ]:

dados = pd.read_csv(BASE_PATH)

with open(CAMINHO_VARIAVEIS_MODELO, "r", encoding="utf-8") as arquivo:
    info_variaveis = json.load(arquivo)

print("Base carregada com sucesso.")
print("Dimensão da base:")
print(dados.shape)

print("\nInformações carregadas do Programa 1:")
print(f"Variável resposta: {info_variaveis['variavel_resposta']}")
print(f"Número de observações: {info_variaveis['n_observacoes']}")
print(f"Número de óbitos: {info_variaveis['n_eventos_obito']}")
print(f"Número de não óbitos: {info_variaveis['n_nao_eventos']}")

print("\nPrimeiras linhas da base:")
display(dados.head())

Base carregada com sucesso.
Dimensão da base:
(470, 26)

Informações carregadas do Programa 1:
Variável resposta: obito_1_ano
Número de observações: 470
Número de óbitos: 70
Número de não óbitos: 400

Primeiras linhas da base:

,obito_1_ano,constante,"C(diagnostico, Treatment(reference='DGN3'))[T.DGN1]","C(diagnostico, Treatment(reference='DGN3'))[T.DGN2]","C(diagnostico, Treatment(reference='DGN3'))[T.DGN4]","C(diagnostico, Treatment(reference='DGN3'))[T.DGN5]","C(diagnostico, Treatment(reference='DGN3'))[T.DGN6]","C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]","C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ0]","C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ2]",...,hemoptise_antes_cirurgia,dispneia_antes_cirurgia,tosse_antes_cirurgia,fraqueza_antes_cirurgia,diabetes_mellitus_tipo_2,infarto_miocardio_ate_6_meses,doenca_arterial_periferica,tabagismo,asma,idade
0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,60.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,51.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,59.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.0
4,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,73.0

In [ ]:

y = dados[VAR_RESPOSTA].astype(float)

variaveis_modelo = info_variaveis["variaveis_modelo"]

variaveis_modelo = [v for v in variaveis_modelo if v != VAR_RESPOSTA]

X = dados[variaveis_modelo].copy()

for coluna in X.columns:
    X[coluna] = pd.to_numeric(X[coluna], errors="coerce")

faltantes = X.isna().sum()
faltantes = faltantes[faltantes > 0]

if len(faltantes) > 0:
    print("Variáveis com valores ausentes:")
    display(faltantes.to_frame("n_faltantes"))
    raise ValueError("Existem valores ausentes na matriz X.")

print("Dimensão de y:")
print(y.shape)

print("\nDimensão de X:")
print(X.shape)

print("\nVariáveis carregadas para o processo de seleção:")
display(pd.DataFrame({"variavel": X.columns}))

Dimensão de y:
(470,)

Dimensão de X:
(470, 25)

Variáveis carregadas para o processo de seleção:

                                             variavel
0                                           constante
1   C(diagnostico, Treatment(reference='DGN3'))[T....
2   C(diagnostico, Treatment(reference='DGN3'))[T....
3   C(diagnostico, Treatment(reference='DGN3'))[T....
4   C(diagnostico, Treatment(reference='DGN3'))[T....
5   C(diagnostico, Treatment(reference='DGN3'))[T....
6   C(diagnostico, Treatment(reference='DGN3'))[T....
7   C(estado_desempenho_zubrod, Treatment(referenc...
8   C(estado_desempenho_zubrod, Treatment(referenc...
9   C(tamanho_tumor_tnm, Treatment(reference='OC11...
10  C(tamanho_tumor_tnm, Treatment(reference='OC11...
11  C(tamanho_tumor_tnm, Treatment(reference='OC11...
12                           capacidade_vital_forcada
13                      volume_expiratorio_forcado_1s
14                                 dor_antes_cirurgia
15                           hemoptise_antes_cirurgia
16                            dispneia_antes_cirurgia
17                               tosse_antes_cirurgia
18                            fraqueza_antes_cirurgia
19                           diabetes_mellitus_tipo_2
20                      infarto_miocardio_ate_6_meses
21                         doenca_arterial_periferica
22                                          tabagismo
23                                               asma
24                                              idade

In [ ]:

pd.set_option("display.max_colwidth", None)


nomes_constante = ["const", "constante"]

colunas_constante = [
    coluna for coluna in X.columns
    if coluna in nomes_constante or X[coluna].nunique() == 1
]

print("Colunas constantes identificadas:")
print(colunas_constante)


def identificar_bloco(coluna):

    if coluna in colunas_constante:
        return None

    if coluna.startswith("C("):
        inicio = coluna.find("C(") + 2
        fim = coluna.find(",")
        
        if fim != -1:
            return coluna[inicio:fim].strip()

    return coluna

blocos = {}

for coluna in X.columns:
    nome_bloco = identificar_bloco(coluna)
    
    if nome_bloco is None:
        continue
    
    if nome_bloco not in blocos:
        blocos[nome_bloco] = []
    
    blocos[nome_bloco].append(coluna)

tabela_blocos = pd.DataFrame([
    {
        "bloco": nome_bloco,
        "n_colunas": len(colunas),
        "colunas": ", ".join(colunas)
    }
    for nome_bloco, colunas in blocos.items()
])

display(tabela_blocos)

Colunas constantes identificadas:
['constante']

,bloco,n_colunas,colunas
0,diagnostico,6,"C(diagnostico, Treatment(reference='DGN3'))[T.DGN1], C(diagnostico, Treatment(reference='DGN3'))[T.DGN2], C(diagnostico, Treatment(reference='DGN3'))[T.DGN4], C(diagnostico, Treatment(reference='DGN3'))[T.DGN5], C(diagnostico, Treatment(reference='DGN3'))[T.DGN6], C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]"
1,estado_desempenho_zubrod,2,"C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ0], C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ2]"
2,tamanho_tumor_tnm,3,"C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]"
3,capacidade_vital_forcada,1,capacidade_vital_forcada
4,volume_expiratorio_forcado_1s,1,volume_expiratorio_forcado_1s
5,dor_antes_cirurgia,1,dor_antes_cirurgia
6,hemoptise_antes_cirurgia,1,hemoptise_antes_cirurgia
7,dispneia_antes_cirurgia,1,dispneia_antes_cirurgia
8,tosse_antes_cirurgia,1,tosse_antes_cirurgia
9,fraqueza_antes_cirurgia,1,fraqueza_antes_cirurgia
10,diabetes_mellitus_tipo_2,1,diabetes_mellitus_tipo_2
11,infarto_miocardio_ate_6_meses,1,infarto_miocardio_ate_6_meses
12,doenca_arterial_periferica,1,doenca_arterial_periferica
13,tabagismo,1,tabagismo
14,asma,1,asma
15,idade,1,idade

In [ ]:

def ajustar_modelo(y, X):

    modelo = sm.GLM(
        y,
        X,
        family=sm.families.Binomial()
    )
    
    resultado = modelo.fit(maxiter=200)
    
    return resultado


def teste_wald_bloco(resultado, colunas_bloco):

    beta = resultado.params[colunas_bloco].values
    matriz_cov = resultado.cov_params().loc[colunas_bloco, colunas_bloco].values
    
    q = len(colunas_bloco)
    
    try:
        matriz_cov_inv = np.linalg.inv(matriz_cov)
    except np.linalg.LinAlgError:
        matriz_cov_inv = np.linalg.pinv(matriz_cov)
    
    estatistica_wald = float(beta.T @ matriz_cov_inv @ beta)
    p_valor_wald = float(chi2.sf(estatistica_wald, q))
    
    return estatistica_wald, p_valor_wald, q


def teste_deviance_modelo_reduzido(y, X_atual, resultado_atual, colunas_remover):

    X_reduzido = X_atual.drop(columns=colunas_remover)
    
    resultado_reduzido = ajustar_modelo(y, X_reduzido)
    
    delta_deviance = float(resultado_reduzido.deviance - resultado_atual.deviance)
    
    if delta_deviance < 0:
        delta_deviance = 0.0
    
    q = len(colunas_remover)
    p_valor_deviance = float(chi2.sf(delta_deviance, q))
    
    return resultado_reduzido, delta_deviance, p_valor_deviance, q

In [ ]:

X_atual = X.copy()
blocos_ativos = blocos.copy()

historico_selecao = []

iteracao = 1

while True:
    
    print("=" * 80)
    print(f"Iteração {iteracao}")
    print("=" * 80)
    
    resultado_atual = ajustar_modelo(y, X_atual)
    
    print(f"Deviance do modelo atual: {resultado_atual.deviance:.6f}")
    print(f"Número de parâmetros: {len(resultado_atual.params)}")
    print(f"Número de blocos ativos: {len(blocos_ativos)}")
    
    resultados_iteracao = []
    
    for nome_bloco, colunas_bloco in blocos_ativos.items():
        
        colunas_bloco = [col for col in colunas_bloco if col in X_atual.columns]
        
        if len(colunas_bloco) == 0:
            continue
        
        estat_wald, p_wald, gl_wald = teste_wald_bloco(
            resultado_atual,
            colunas_bloco
        )
        
        try:
            resultado_reduzido, delta_dev, p_dev, gl_dev = teste_deviance_modelo_reduzido(
                y,
                X_atual,
                resultado_atual,
                colunas_bloco
            )
            
            erro_ajuste = ""
        
        except Exception as erro:
            delta_dev = np.nan
            p_dev = np.nan
            gl_dev = len(colunas_bloco)
            erro_ajuste = str(erro)
        
        remover = (
            p_wald > ALPHA
            and p_dev > ALPHA
            and erro_ajuste == ""
        )
        
        resultados_iteracao.append({
            "iteracao": iteracao,
            "bloco": nome_bloco,
            "n_parametros_bloco": len(colunas_bloco),
            "estatistica_wald": estat_wald,
            "p_valor_wald": p_wald,
            "delta_deviance": delta_dev,
            "p_valor_deviance": p_dev,
            "remover_pelos_criterios": remover,
            "colunas_do_bloco": ", ".join(colunas_bloco),
            "erro_ajuste": erro_ajuste
        })
    
    tabela_iteracao = pd.DataFrame(resultados_iteracao)
    
    tabela_iteracao = tabela_iteracao.sort_values(
        by=["remover_pelos_criterios", "p_valor_wald", "p_valor_deviance"],
        ascending=[False, False, False]
    ).reset_index(drop=True)
    
    display(tabela_iteracao)
    
    candidatos_remocao = tabela_iteracao[
        tabela_iteracao["remover_pelos_criterios"] == True
    ].copy()
    
    if candidatos_remocao.empty:
        print("\nNenhum bloco atende simultaneamente aos dois critérios de remoção.")
        print("Processo de seleção finalizado.")
        break
    
    bloco_removido = candidatos_remocao.iloc[0]["bloco"]
    colunas_removidas = blocos_ativos[bloco_removido]
    
    print("\nBloco removido nesta iteração:")
    print(bloco_removido)
    
    print("\nColunas removidas:")
    for coluna in colunas_removidas:
        print(f"- {coluna}")
    

    historico_selecao.append({
        "iteracao": iteracao,
        "bloco_removido": bloco_removido,
        "n_parametros_removidos": len(colunas_removidas),
        "p_valor_wald": float(candidatos_remocao.iloc[0]["p_valor_wald"]),
        "p_valor_deviance": float(candidatos_remocao.iloc[0]["p_valor_deviance"]),
        "delta_deviance": float(candidatos_remocao.iloc[0]["delta_deviance"]),
        "deviance_modelo_antes": float(resultado_atual.deviance),
        "colunas_removidas": ", ".join(colunas_removidas)
    })
    

    X_atual = X_atual.drop(columns=colunas_removidas)
    del blocos_ativos[bloco_removido]
    
    iteracao += 1

================================================================================
Iteração 1
================================================================================
Deviance do modelo atual: 341.187221
Número de parâmetros: 25
Número de blocos ativos: 16

,iteracao,bloco,n_parametros_bloco,estatistica_wald,p_valor_wald,delta_deviance,p_valor_deviance,remover_pelos_criterios,colunas_do_bloco,erro_ajuste
0,1,asma,1,3.656536e-07,0.999518,0.303253,0.581850,True,asma,
1,1,infarto_miocardio_ate_6_meses,1,3.867849e-07,0.999504,0.563121,0.453005,True,infarto_miocardio_ate_6_meses,
2,1,doenca_arterial_periferica,1,9.520113e-03,0.922273,0.009629,0.921833,True,doenca_arterial_periferica,
3,1,estado_desempenho_zubrod,2,8.073909e-01,0.667847,0.808683,0.667416,True,"C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ0], C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ2]",
4,1,hemoptise_antes_cirurgia,1,2.006611e-01,0.654188,0.197459,0.656780,True,hemoptise_antes_cirurgia,
5,1,idade,1,2.758390e-01,0.599442,0.275079,0.599945,True,idade,
6,1,tosse_antes_cirurgia,1,1.429446e+00,0.231855,1.481631,0.223519,True,tosse_antes_cirurgia,
7,1,capacidade_vital_forcada,1,1.510292e+00,0.219094,1.544362,0.213970,True,capacidade_vital_forcada,
8,1,dor_antes_cirurgia,1,1.657924e+00,0.197884,1.576328,0.209290,True,dor_antes_cirurgia,
9,1,fraqueza_antes_cirurgia,1,1.694964e+00,0.192948,1.637602,0.200655,True,fraqueza_antes_cirurgia,
10,1,volume_expiratorio_forcado_1s,1,2.879481e+00,0.089715,4.034735,0.044573,False,volume_expiratorio_forcado_1s,
11,1,diabetes_mellitus_tipo_2,1,4.346196e+00,0.037092,3.983474,0.045949,False,diabetes_mellitus_tipo_2,
12,1,tabagismo,1,4.718479e+00,0.029840,5.695593,0.017008,False,tabagismo,
13,1,tamanho_tumor_tnm,3,9.099554e+00,0.027996,8.852938,0.031311,False,"C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]",
14,1,diagnostico,6,1.849961e+01,0.005098,18.091891,0.006007,False,"C(diagnostico, Treatment(reference='DGN3'))[T.DGN1], C(diagnostico, Treatment(reference='DGN3'))[T.DGN2], C(diagnostico, Treatment(reference='DGN3'))[T.DGN4], C(diagnostico, Treatment(reference='DGN3'))[T.DGN5], C(diagnostico, Treatment(reference='DGN3'))[T.DGN6], C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]",
15,1,dispneia_antes_cirurgia,1,7.900699e+00,0.004942,7.159048,0.007459,False,dispneia_antes_cirurgia,

Bloco removido nesta iteração:
asma

Colunas removidas:
- asma
================================================================================
Iteração 2
================================================================================
Deviance do modelo atual: 341.490473
Número de parâmetros: 24
Número de blocos ativos: 15

,iteracao,bloco,n_parametros_bloco,estatistica_wald,p_valor_wald,delta_deviance,p_valor_deviance,remover_pelos_criterios,colunas_do_bloco,erro_ajuste
0,2,infarto_miocardio_ate_6_meses,1,3.865668e-07,0.999504,0.561148,0.453798,True,infarto_miocardio_ate_6_meses,
1,2,doenca_arterial_periferica,1,9.520337e-03,0.922272,0.009629,0.921832,True,doenca_arterial_periferica,
2,2,estado_desempenho_zubrod,2,7.824627e-01,0.676224,0.783687,0.675810,True,"C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ0], C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ2]",
3,2,hemoptise_antes_cirurgia,1,2.067504e-01,0.649326,0.203400,0.651990,True,hemoptise_antes_cirurgia,
4,2,idade,1,2.693516e-01,0.603767,0.268639,0.604246,True,idade,
5,2,tosse_antes_cirurgia,1,1.447790e+00,0.228883,1.501109,0.220501,True,tosse_antes_cirurgia,
6,2,capacidade_vital_forcada,1,1.467239e+00,0.225782,1.500112,0.220654,True,capacidade_vital_forcada,
7,2,dor_antes_cirurgia,1,1.663892e+00,0.197079,1.581950,0.208480,True,dor_antes_cirurgia,
8,2,fraqueza_antes_cirurgia,1,1.702218e+00,0.191998,1.644456,0.199715,True,fraqueza_antes_cirurgia,
9,2,volume_expiratorio_forcado_1s,1,2.865810e+00,0.090480,4.010478,0.045218,False,volume_expiratorio_forcado_1s,
10,2,diabetes_mellitus_tipo_2,1,4.382289e+00,0.036314,4.014878,0.045100,False,diabetes_mellitus_tipo_2,
11,2,tabagismo,1,4.762448e+00,0.029087,5.757859,0.016415,False,tabagismo,
12,2,tamanho_tumor_tnm,3,9.104625e+00,0.027932,8.852846,0.031313,False,"C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]",
13,2,diagnostico,6,1.860249e+01,0.004890,18.176230,0.005807,False,"C(diagnostico, Treatment(reference='DGN3'))[T.DGN1], C(diagnostico, Treatment(reference='DGN3'))[T.DGN2], C(diagnostico, Treatment(reference='DGN3'))[T.DGN4], C(diagnostico, Treatment(reference='DGN3'))[T.DGN5], C(diagnostico, Treatment(reference='DGN3'))[T.DGN6], C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]",
14,2,dispneia_antes_cirurgia,1,7.930649e+00,0.004860,7.184133,0.007355,False,dispneia_antes_cirurgia,

Bloco removido nesta iteração:
infarto_miocardio_ate_6_meses

Colunas removidas:
- infarto_miocardio_ate_6_meses
================================================================================
Iteração 3
================================================================================
Deviance do modelo atual: 342.051622
Número de parâmetros: 23
Número de blocos ativos: 14

,iteracao,bloco,n_parametros_bloco,estatistica_wald,p_valor_wald,delta_deviance,p_valor_deviance,remover_pelos_criterios,colunas_do_bloco,erro_ajuste
0,3,doenca_arterial_periferica,1,0.008862,0.924999,0.008960,0.924588,True,doenca_arterial_periferica,
1,3,estado_desempenho_zubrod,2,0.795699,0.671763,0.796886,0.671364,True,"C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ0], C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ2]",
2,3,hemoptise_antes_cirurgia,1,0.220610,0.638575,0.216908,0.641406,True,hemoptise_antes_cirurgia,
3,3,idade,1,0.246245,0.619732,0.245644,0.620159,True,idade,
4,3,tosse_antes_cirurgia,1,1.419833,0.233431,1.471669,0.225083,True,tosse_antes_cirurgia,
5,3,capacidade_vital_forcada,1,1.431771,0.231476,1.463497,0.226375,True,capacidade_vital_forcada,
6,3,fraqueza_antes_cirurgia,1,1.588067,0.207603,1.535214,0.215332,True,fraqueza_antes_cirurgia,
7,3,dor_antes_cirurgia,1,1.653045,0.198545,1.571705,0.209960,True,dor_antes_cirurgia,
8,3,volume_expiratorio_forcado_1s,1,2.864582,0.090549,4.005120,0.045362,False,volume_expiratorio_forcado_1s,
9,3,diabetes_mellitus_tipo_2,1,4.456588,0.034767,4.078886,0.043422,False,diabetes_mellitus_tipo_2,
10,3,tabagismo,1,4.746957,0.029350,5.737913,0.016603,False,tabagismo,
11,3,tamanho_tumor_tnm,3,9.144333,0.027432,8.881068,0.030915,False,"C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]",
12,3,dispneia_antes_cirurgia,1,7.938546,0.004839,7.190354,0.007330,False,dispneia_antes_cirurgia,
13,3,diagnostico,6,18.686126,0.004728,18.255572,0.005624,False,"C(diagnostico, Treatment(reference='DGN3'))[T.DGN1], C(diagnostico, Treatment(reference='DGN3'))[T.DGN2], C(diagnostico, Treatment(reference='DGN3'))[T.DGN4], C(diagnostico, Treatment(reference='DGN3'))[T.DGN5], C(diagnostico, Treatment(reference='DGN3'))[T.DGN6], C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]",

Bloco removido nesta iteração:
doenca_arterial_periferica

Colunas removidas:
- doenca_arterial_periferica
================================================================================
Iteração 4
================================================================================
Deviance do modelo atual: 342.060582
Número de parâmetros: 22
Número de blocos ativos: 13

,iteracao,bloco,n_parametros_bloco,estatistica_wald,p_valor_wald,delta_deviance,p_valor_deviance,remover_pelos_criterios,colunas_do_bloco,erro_ajuste
0,4,estado_desempenho_zubrod,2,0.817335,0.664535,0.818591,0.664118,True,"C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ0], C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ2]",
1,4,hemoptise_antes_cirurgia,1,0.212734,0.644633,0.209330,0.647293,True,hemoptise_antes_cirurgia,
2,4,idade,1,0.251969,0.615692,0.251314,0.616152,True,idade,
3,4,capacidade_vital_forcada,1,1.427066,0.232244,1.458640,0.227147,True,capacidade_vital_forcada,
4,4,tosse_antes_cirurgia,1,1.436935,0.230636,1.490255,0.222177,True,tosse_antes_cirurgia,
5,4,fraqueza_antes_cirurgia,1,1.586459,0.207833,1.533687,0.215560,True,fraqueza_antes_cirurgia,
6,4,dor_antes_cirurgia,1,1.678655,0.195103,1.594979,0.206616,True,dor_antes_cirurgia,
7,4,volume_expiratorio_forcado_1s,1,2.856232,0.091021,3.996161,0.045604,False,volume_expiratorio_forcado_1s,
8,4,diabetes_mellitus_tipo_2,1,4.441951,0.035066,4.069983,0.043652,False,diabetes_mellitus_tipo_2,
9,4,tabagismo,1,4.746308,0.029361,5.737373,0.016608,False,tabagismo,
10,4,tamanho_tumor_tnm,3,9.177660,0.027020,8.914533,0.030449,False,"C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]",
11,4,dispneia_antes_cirurgia,1,8.014919,0.004639,7.243652,0.007115,False,dispneia_antes_cirurgia,
12,4,diagnostico,6,18.749438,0.004608,18.361187,0.005390,False,"C(diagnostico, Treatment(reference='DGN3'))[T.DGN1], C(diagnostico, Treatment(reference='DGN3'))[T.DGN2], C(diagnostico, Treatment(reference='DGN3'))[T.DGN4], C(diagnostico, Treatment(reference='DGN3'))[T.DGN5], C(diagnostico, Treatment(reference='DGN3'))[T.DGN6], C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]",

Bloco removido nesta iteração:
estado_desempenho_zubrod

Colunas removidas:
- C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ0]
- C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ2]
================================================================================
Iteração 5
================================================================================
Deviance do modelo atual: 342.879172
Número de parâmetros: 20
Número de blocos ativos: 12

,iteracao,bloco,n_parametros_bloco,estatistica_wald,p_valor_wald,delta_deviance,p_valor_deviance,remover_pelos_criterios,colunas_do_bloco,erro_ajuste
0,5,idade,1,0.164045,0.685460,0.163702,0.685771,True,idade,
1,5,hemoptise_antes_cirurgia,1,0.237115,0.626297,0.233164,0.629188,True,hemoptise_antes_cirurgia,
2,5,tosse_antes_cirurgia,1,0.787637,0.374816,0.811807,0.367586,True,tosse_antes_cirurgia,
3,5,capacidade_vital_forcada,1,1.252033,0.263165,1.276574,0.258537,True,capacidade_vital_forcada,
4,5,dor_antes_cirurgia,1,1.287273,0.256551,1.222299,0.268910,True,dor_antes_cirurgia,
5,5,fraqueza_antes_cirurgia,1,1.792761,0.180590,1.733740,0.187934,True,fraqueza_antes_cirurgia,
6,5,volume_expiratorio_forcado_1s,1,2.449135,0.117590,3.419098,0.064446,True,volume_expiratorio_forcado_1s,
7,5,diabetes_mellitus_tipo_2,1,4.232255,0.039663,3.879585,0.048877,False,diabetes_mellitus_tipo_2,
8,5,tabagismo,1,4.540063,0.033110,5.486745,0.019161,False,tabagismo,
9,5,tamanho_tumor_tnm,3,9.669180,0.021598,9.354952,0.024926,False,"C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]",
10,5,dispneia_antes_cirurgia,1,7.925375,0.004875,7.136490,0.007553,False,dispneia_antes_cirurgia,
11,5,diagnostico,6,19.018469,0.004133,18.470841,0.005157,False,"C(diagnostico, Treatment(reference='DGN3'))[T.DGN1], C(diagnostico, Treatment(reference='DGN3'))[T.DGN2], C(diagnostico, Treatment(reference='DGN3'))[T.DGN4], C(diagnostico, Treatment(reference='DGN3'))[T.DGN5], C(diagnostico, Treatment(reference='DGN3'))[T.DGN6], C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]",

Bloco removido nesta iteração:
idade

Colunas removidas:
- idade
================================================================================
Iteração 6
================================================================================
Deviance do modelo atual: 343.042875
Número de parâmetros: 19
Número de blocos ativos: 11

,iteracao,bloco,n_parametros_bloco,estatistica_wald,p_valor_wald,delta_deviance,p_valor_deviance,remover_pelos_criterios,colunas_do_bloco,erro_ajuste
0,6,hemoptise_antes_cirurgia,1,0.233195,0.629165,0.229320,0.632028,True,hemoptise_antes_cirurgia,
1,6,tosse_antes_cirurgia,1,0.734366,0.391472,0.756405,0.384456,True,tosse_antes_cirurgia,
2,6,capacidade_vital_forcada,1,1.103265,0.293551,1.125370,0.288765,True,capacidade_vital_forcada,
3,6,dor_antes_cirurgia,1,1.262258,0.261224,1.198380,0.273646,True,dor_antes_cirurgia,
4,6,fraqueza_antes_cirurgia,1,1.646881,0.199384,1.593015,0.206896,True,fraqueza_antes_cirurgia,
5,6,volume_expiratorio_forcado_1s,1,2.381558,0.122775,3.315437,0.068632,True,volume_expiratorio_forcado_1s,
6,6,diabetes_mellitus_tipo_2,1,4.137860,0.041934,3.796336,0.051365,False,diabetes_mellitus_tipo_2,
7,6,tabagismo,1,4.552485,0.032871,5.506346,0.018948,False,tabagismo,
8,6,tamanho_tumor_tnm,3,9.764601,0.020677,9.408398,0.024326,False,"C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]",
9,6,dispneia_antes_cirurgia,1,7.742344,0.005394,6.993025,0.008183,False,dispneia_antes_cirurgia,
10,6,diagnostico,6,18.884962,0.004362,18.346922,0.005421,False,"C(diagnostico, Treatment(reference='DGN3'))[T.DGN1], C(diagnostico, Treatment(reference='DGN3'))[T.DGN2], C(diagnostico, Treatment(reference='DGN3'))[T.DGN4], C(diagnostico, Treatment(reference='DGN3'))[T.DGN5], C(diagnostico, Treatment(reference='DGN3'))[T.DGN6], C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]",

Bloco removido nesta iteração:
hemoptise_antes_cirurgia

Colunas removidas:
- hemoptise_antes_cirurgia
================================================================================
Iteração 7
================================================================================
Deviance do modelo atual: 343.272195
Número de parâmetros: 18
Número de blocos ativos: 10

,iteracao,bloco,n_parametros_bloco,estatistica_wald,p_valor_wald,delta_deviance,p_valor_deviance,remover_pelos_criterios,colunas_do_bloco,erro_ajuste
0,7,tosse_antes_cirurgia,1,0.798620,0.371506,0.824057,0.363997,True,tosse_antes_cirurgia,
1,7,capacidade_vital_forcada,1,1.253398,0.262904,1.280616,0.257785,True,capacidade_vital_forcada,
2,7,dor_antes_cirurgia,1,1.679268,0.195022,1.570353,0.210156,True,dor_antes_cirurgia,
3,7,fraqueza_antes_cirurgia,1,1.695224,0.192914,1.638931,0.200472,True,fraqueza_antes_cirurgia,
4,7,volume_expiratorio_forcado_1s,1,2.307833,0.128723,3.207398,0.073306,True,volume_expiratorio_forcado_1s,
5,7,diabetes_mellitus_tipo_2,1,4.091229,0.043106,3.754479,0.052666,False,diabetes_mellitus_tipo_2,
6,7,tabagismo,1,4.510542,0.033687,5.457102,0.019489,False,tabagismo,
7,7,tamanho_tumor_tnm,3,9.649601,0.021792,9.280873,0.025780,False,"C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]",
8,7,dispneia_antes_cirurgia,1,8.133815,0.004345,7.310676,0.006855,False,dispneia_antes_cirurgia,
9,7,diagnostico,6,19.185920,0.003861,18.693290,0.004714,False,"C(diagnostico, Treatment(reference='DGN3'))[T.DGN1], C(diagnostico, Treatment(reference='DGN3'))[T.DGN2], C(diagnostico, Treatment(reference='DGN3'))[T.DGN4], C(diagnostico, Treatment(reference='DGN3'))[T.DGN5], C(diagnostico, Treatment(reference='DGN3'))[T.DGN6], C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]",

Bloco removido nesta iteração:
tosse_antes_cirurgia

Colunas removidas:
- tosse_antes_cirurgia
================================================================================
Iteração 8
================================================================================
Deviance do modelo atual: 344.096251
Número de parâmetros: 17
Número de blocos ativos: 9

,iteracao,bloco,n_parametros_bloco,estatistica_wald,p_valor_wald,delta_deviance,p_valor_deviance,remover_pelos_criterios,colunas_do_bloco,erro_ajuste
0,8,capacidade_vital_forcada,1,1.215287,0.270288,1.240907,0.265296,True,capacidade_vital_forcada,
1,8,dor_antes_cirurgia,1,1.440439,0.230068,1.353096,0.244738,True,dor_antes_cirurgia,
2,8,fraqueza_antes_cirurgia,1,2.228698,0.135468,2.137496,0.143736,True,fraqueza_antes_cirurgia,
3,8,volume_expiratorio_forcado_1s,1,2.349548,0.125319,3.288614,0.069762,True,volume_expiratorio_forcado_1s,
4,8,diabetes_mellitus_tipo_2,1,4.165022,0.041267,3.818568,0.050688,False,diabetes_mellitus_tipo_2,
5,8,tabagismo,1,5.224278,0.022274,6.464010,0.011008,False,tabagismo,
6,8,tamanho_tumor_tnm,3,10.831394,0.012673,10.380644,0.015593,False,"C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]",
7,8,diagnostico,6,18.690534,0.004719,18.208891,0.005731,False,"C(diagnostico, Treatment(reference='DGN3'))[T.DGN1], C(diagnostico, Treatment(reference='DGN3'))[T.DGN2], C(diagnostico, Treatment(reference='DGN3'))[T.DGN4], C(diagnostico, Treatment(reference='DGN3'))[T.DGN5], C(diagnostico, Treatment(reference='DGN3'))[T.DGN6], C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]",
8,8,dispneia_antes_cirurgia,1,8.501624,0.003548,7.614357,0.005791,False,dispneia_antes_cirurgia,

Bloco removido nesta iteração:
capacidade_vital_forcada

Colunas removidas:
- capacidade_vital_forcada
================================================================================
Iteração 9
================================================================================
Deviance do modelo atual: 345.337159
Número de parâmetros: 16
Número de blocos ativos: 8

,iteracao,bloco,n_parametros_bloco,estatistica_wald,p_valor_wald,delta_deviance,p_valor_deviance,remover_pelos_criterios,colunas_do_bloco,erro_ajuste
0,9,dor_antes_cirurgia,1,1.347038,0.245797,1.268849,0.259983,True,dor_antes_cirurgia,
1,9,volume_expiratorio_forcado_1s,1,2.393520,0.121839,3.419820,0.064418,True,volume_expiratorio_forcado_1s,
2,9,fraqueza_antes_cirurgia,1,2.465994,0.116334,2.359051,0.124558,True,fraqueza_antes_cirurgia,
3,9,diabetes_mellitus_tipo_2,1,4.882468,0.027131,4.441357,0.035078,False,diabetes_mellitus_tipo_2,
4,9,tabagismo,1,5.235771,0.022127,6.472029,0.010959,False,tabagismo,
5,9,tamanho_tumor_tnm,3,10.584397,0.014199,10.138916,0.017421,False,"C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]",
6,9,diagnostico,6,18.053100,0.006101,17.657794,0.007147,False,"C(diagnostico, Treatment(reference='DGN3'))[T.DGN1], C(diagnostico, Treatment(reference='DGN3'))[T.DGN2], C(diagnostico, Treatment(reference='DGN3'))[T.DGN4], C(diagnostico, Treatment(reference='DGN3'))[T.DGN5], C(diagnostico, Treatment(reference='DGN3'))[T.DGN6], C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]",
7,9,dispneia_antes_cirurgia,1,8.340165,0.003878,7.451913,0.006337,False,dispneia_antes_cirurgia,

Bloco removido nesta iteração:
dor_antes_cirurgia

Colunas removidas:
- dor_antes_cirurgia
================================================================================
Iteração 10
================================================================================
Deviance do modelo atual: 346.606008
Número de parâmetros: 15
Número de blocos ativos: 7

,iteracao,bloco,n_parametros_bloco,estatistica_wald,p_valor_wald,delta_deviance,p_valor_deviance,remover_pelos_criterios,colunas_do_bloco,erro_ajuste
0,10,volume_expiratorio_forcado_1s,1,1.968659,0.160590,2.781962,0.095331,True,volume_expiratorio_forcado_1s,
1,10,fraqueza_antes_cirurgia,1,2.219905,0.136241,2.126732,0.144749,True,fraqueza_antes_cirurgia,
2,10,tabagismo,1,4.952451,0.026054,6.084762,0.013635,False,tabagismo,
3,10,diabetes_mellitus_tipo_2,1,5.221000,0.022316,4.731590,0.029613,False,diabetes_mellitus_tipo_2,
4,10,tamanho_tumor_tnm,3,11.412181,0.009694,10.891447,0.012328,False,"C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]",
5,10,diagnostico,6,17.852754,0.006611,17.551447,0.007457,False,"C(diagnostico, Treatment(reference='DGN3'))[T.DGN1], C(diagnostico, Treatment(reference='DGN3'))[T.DGN2], C(diagnostico, Treatment(reference='DGN3'))[T.DGN4], C(diagnostico, Treatment(reference='DGN3'))[T.DGN5], C(diagnostico, Treatment(reference='DGN3'))[T.DGN6], C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]",
6,10,dispneia_antes_cirurgia,1,8.369585,0.003816,7.460244,0.006308,False,dispneia_antes_cirurgia,

Bloco removido nesta iteração:
volume_expiratorio_forcado_1s

Colunas removidas:
- volume_expiratorio_forcado_1s
================================================================================
Iteração 11
================================================================================
Deviance do modelo atual: 349.387970
Número de parâmetros: 14
Número de blocos ativos: 6

,iteracao,bloco,n_parametros_bloco,estatistica_wald,p_valor_wald,delta_deviance,p_valor_deviance,remover_pelos_criterios,colunas_do_bloco,erro_ajuste
0,11,fraqueza_antes_cirurgia,1,2.626412,0.105099,2.506314,0.113391,True,fraqueza_antes_cirurgia,
1,11,diabetes_mellitus_tipo_2,1,5.390816,0.020243,4.874221,0.027261,False,diabetes_mellitus_tipo_2,
2,11,tabagismo,1,5.492146,0.019102,6.810243,0.009064,False,tabagismo,
3,11,tamanho_tumor_tnm,3,11.382932,0.009826,10.843391,0.012604,False,"C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]",
4,11,diagnostico,6,17.013894,0.009232,16.500192,0.011307,False,"C(diagnostico, Treatment(reference='DGN3'))[T.DGN1], C(diagnostico, Treatment(reference='DGN3'))[T.DGN2], C(diagnostico, Treatment(reference='DGN3'))[T.DGN4], C(diagnostico, Treatment(reference='DGN3'))[T.DGN5], C(diagnostico, Treatment(reference='DGN3'))[T.DGN6], C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]",
5,11,dispneia_antes_cirurgia,1,6.916107,0.008542,6.147015,0.013163,False,dispneia_antes_cirurgia,

Bloco removido nesta iteração:
fraqueza_antes_cirurgia

Colunas removidas:
- fraqueza_antes_cirurgia
================================================================================
Iteração 12
================================================================================
Deviance do modelo atual: 351.894284
Número de parâmetros: 13
Número de blocos ativos: 5

,iteracao,bloco,n_parametros_bloco,estatistica_wald,p_valor_wald,delta_deviance,p_valor_deviance,remover_pelos_criterios,colunas_do_bloco,erro_ajuste
0,12,diabetes_mellitus_tipo_2,1,5.748853,0.016499,5.168041,0.023006,False,diabetes_mellitus_tipo_2,
1,12,tabagismo,1,6.134679,0.013256,7.747101,0.005380,False,tabagismo,
2,12,tamanho_tumor_tnm,3,10.961826,0.011934,10.327606,0.015977,False,"C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13], C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]",
3,12,dispneia_antes_cirurgia,1,6.323880,0.011912,5.640174,0.017553,False,dispneia_antes_cirurgia,
4,12,diagnostico,6,17.319505,0.008178,16.889593,0.009698,False,"C(diagnostico, Treatment(reference='DGN3'))[T.DGN1], C(diagnostico, Treatment(reference='DGN3'))[T.DGN2], C(diagnostico, Treatment(reference='DGN3'))[T.DGN4], C(diagnostico, Treatment(reference='DGN3'))[T.DGN5], C(diagnostico, Treatment(reference='DGN3'))[T.DGN6], C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]",

Nenhum bloco atende simultaneamente aos dois critérios de remoção.
Processo de seleção finalizado.

In [ ]:

if len(historico_selecao) > 0:
    tabela_historico = pd.DataFrame(historico_selecao)
else:
    tabela_historico = pd.DataFrame(columns=[
        "iteracao",
        "bloco_removido",
        "n_parametros_removidos",
        "p_valor_wald",
        "p_valor_deviance",
        "delta_deviance",
        "deviance_modelo_antes",
        "colunas_removidas"
    ])

tabela_historico.to_csv(CAMINHO_HISTORICO_SELECAO, index=False, encoding="utf-8-sig")

print("Histórico da seleção salvo em:")
print(CAMINHO_HISTORICO_SELECAO)

print("\nHistórico da seleção:")
display(tabela_historico)

Histórico da seleção salvo em:
outputs\historico_selecao.csv

Histórico da seleção:

,iteracao,bloco_removido,n_parametros_removidos,p_valor_wald,p_valor_deviance,delta_deviance,deviance_modelo_antes,colunas_removidas
0,1,asma,1,0.999518,0.581850,0.303253,341.187221,asma
1,2,infarto_miocardio_ate_6_meses,1,0.999504,0.453798,0.561148,341.490473,infarto_miocardio_ate_6_meses
2,3,doenca_arterial_periferica,1,0.924999,0.924588,0.008960,342.051622,doenca_arterial_periferica
3,4,estado_desempenho_zubrod,2,0.664535,0.664118,0.818591,342.060582,"C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ0], C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ2]"
4,5,idade,1,0.685460,0.685771,0.163702,342.879172,idade
5,6,hemoptise_antes_cirurgia,1,0.629165,0.632028,0.229320,343.042875,hemoptise_antes_cirurgia
6,7,tosse_antes_cirurgia,1,0.371506,0.363997,0.824057,343.272195,tosse_antes_cirurgia
7,8,capacidade_vital_forcada,1,0.270288,0.265296,1.240907,344.096251,capacidade_vital_forcada
8,9,dor_antes_cirurgia,1,0.245797,0.259983,1.268849,345.337159,dor_antes_cirurgia
9,10,volume_expiratorio_forcado_1s,1,0.160590,0.095331,2.781962,346.606008,volume_expiratorio_forcado_1s
10,11,fraqueza_antes_cirurgia,1,0.105099,0.113391,2.506314,349.387970,fraqueza_antes_cirurgia

In [ ]:

resultado_final = ajustar_modelo(y, X_atual)

resultado_final.save(str(CAMINHO_MODELO_FINAL), remove_data=False)

print("Modelo final salvo em:")
print(CAMINHO_MODELO_FINAL)

print("\nResumo do modelo final:")
print(resultado_final.summary())

Modelo final salvo em:
outputs\modelo_final.pkl

Resumo do modelo final:
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:            obito_1_ano   No. Observations:                  470
Model:                            GLM   Df Residuals:                      457
Model Family:                Binomial   Df Model:                           12
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -175.95
Date:                Fri, 19 Jun 2026   Deviance:                       351.89
Time:                        09:07:14   Pearson chi2:                     437.
No. Iterations:                    20   Pseudo R-squ. (CS):            0.08881
Covariance Type:            nonrobust
=============================================================================================================================
                                                                coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------------------
constante                                                    -3.5903      0.543     -6.609      0.000      -4.655      -2.526
C(diagnostico, Treatment(reference='DGN3'))[T.DGN1]         -19.5674   2.92e+04     -0.001      0.999   -5.73e+04    5.73e+04
C(diagnostico, Treatment(reference='DGN3'))[T.DGN2]           0.4832      0.402      1.202      0.229      -0.305       1.271
C(diagnostico, Treatment(reference='DGN3'))[T.DGN4]           0.3239      0.456      0.710      0.478      -0.570       1.218
C(diagnostico, Treatment(reference='DGN3'))[T.DGN5]           2.0578      0.573      3.592      0.000       0.935       3.181
C(diagnostico, Treatment(reference='DGN3'))[T.DGN6]         -19.1338   1.44e+04     -0.001      0.999   -2.83e+04    2.82e+04
C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]           3.3996      1.508      2.254      0.024       0.444       6.355
C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12]     0.3815      0.318      1.200      0.230      -0.241       1.004
C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13]     1.2049      0.603      1.998      0.046       0.023       2.387
C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]     1.7591      0.589      2.987      0.003       0.605       2.913
dispneia_antes_cirurgia                                       1.1422      0.454      2.515      0.012       0.252       2.032
diabetes_mellitus_tipo_2                                      1.0287      0.429      2.398      0.016       0.188       1.870
tabagismo                                                     1.2102      0.489      2.477      0.013       0.253       2.168
=============================================================================================================================

In [ ]:

informacoes_finais = {
    "arquivo_base": str(BASE_PATH),
    "variavel_resposta": VAR_RESPOSTA,
    "alpha": ALPHA,
    "criterio_remocao": "Remover somente se p_valor_wald > alpha e p_valor_deviance > alpha",
    "n_observacoes": int(resultado_final.nobs),
    "n_eventos_obito": int(y.sum()),
    "n_nao_eventos": int((1 - y).sum()),
    "variaveis_modelo_final": X_atual.columns.tolist(),
    "variaveis_explicativas_modelo_final": [
        col for col in X_atual.columns if col not in ["const", "constante"]
    ],
    "blocos_finais": blocos_ativos,
    "colunas_constantes": colunas_constante,
    "n_parametros_modelo_final": int(len(resultado_final.params)),
    "deviance_modelo_final": float(resultado_final.deviance),
    "graus_liberdade_residuo": int(resultado_final.df_resid),
    "log_verossimilhanca": float(resultado_final.llf),
    "blocos_removidos": tabela_historico["bloco_removido"].tolist()
}

with open(CAMINHO_VARIAVEIS_FINAIS, "w", encoding="utf-8") as arquivo:
    json.dump(informacoes_finais, arquivo, ensure_ascii=False, indent=4)

print("Informações das variáveis finais salvas em:")
print(CAMINHO_VARIAVEIS_FINAIS)

Informações das variáveis finais salvas em:
outputs\variaveis_finais.json

In [ ]:

resumo_selecao = pd.DataFrame({
    "medida": [
        "n_variaveis_inicio",
        "n_variaveis_final",
        "n_blocos_inicio",
        "n_blocos_final",
        "n_blocos_removidos",
        "deviance_modelo_completo",
        "deviance_modelo_final",
        "log_verossimilhanca_modelo_final"
    ],
    "valor": [
        len(X.columns),
        len(X_atual.columns),
        len(blocos),
        len(blocos_ativos),
        len(tabela_historico),
        float(info_variaveis["deviance_modelo_completo"]),
        float(resultado_final.deviance),
        float(resultado_final.llf)
    ]
})

display(resumo_selecao)

print("Variáveis que permaneceram no modelo final:")
display(pd.DataFrame({"variavel_final": X_atual.columns}))

                             medida       valor
0                n_variaveis_inicio   25.000000
1                 n_variaveis_final   13.000000
2                   n_blocos_inicio   16.000000
3                    n_blocos_final    5.000000
4                n_blocos_removidos   11.000000
5          deviance_modelo_completo  341.187221
6             deviance_modelo_final  351.894284
7  log_verossimilhanca_modelo_final -175.947142

Variáveis que permaneceram no modelo final:

                                               variavel_final
0                                                   constante
1         C(diagnostico, Treatment(reference='DGN3'))[T.DGN1]
2         C(diagnostico, Treatment(reference='DGN3'))[T.DGN2]
3         C(diagnostico, Treatment(reference='DGN3'))[T.DGN4]
4         C(diagnostico, Treatment(reference='DGN3'))[T.DGN5]
5         C(diagnostico, Treatment(reference='DGN3'))[T.DGN6]
6         C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]
7   C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12]
8   C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13]
9   C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]
10                                    dispneia_antes_cirurgia
11                                   diabetes_mellitus_tipo_2
12                                                  tabagismo

In [ ]:

if len(historico_selecao) > 0:
    tabela_historico = pd.DataFrame(historico_selecao)
else:
    tabela_historico = pd.DataFrame(columns=[
        "iteracao",
        "bloco_removido",
        "n_parametros_removidos",
        "p_valor_wald",
        "p_valor_deviance",
        "delta_deviance",
        "deviance_modelo_antes",
        "colunas_removidas"
    ])

tabela_historico.to_csv(
    CAMINHO_HISTORICO_SELECAO,
    index=False,
    encoding="utf-8-sig"
)

print("Histórico da seleção salvo em:")
print(CAMINHO_HISTORICO_SELECAO)

print("\nHistórico da seleção:")
display(tabela_historico)

Histórico da seleção salvo em:
outputs\historico_selecao.csv

Histórico da seleção:

,iteracao,bloco_removido,n_parametros_removidos,p_valor_wald,p_valor_deviance,delta_deviance,deviance_modelo_antes,colunas_removidas
0,1,asma,1,0.999518,0.581850,0.303253,341.187221,asma
1,2,infarto_miocardio_ate_6_meses,1,0.999504,0.453798,0.561148,341.490473,infarto_miocardio_ate_6_meses
2,3,doenca_arterial_periferica,1,0.924999,0.924588,0.008960,342.051622,doenca_arterial_periferica
3,4,estado_desempenho_zubrod,2,0.664535,0.664118,0.818591,342.060582,"C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ0], C(estado_desempenho_zubrod, Treatment(reference='PRZ1'))[T.PRZ2]"
4,5,idade,1,0.685460,0.685771,0.163702,342.879172,idade
5,6,hemoptise_antes_cirurgia,1,0.629165,0.632028,0.229320,343.042875,hemoptise_antes_cirurgia
6,7,tosse_antes_cirurgia,1,0.371506,0.363997,0.824057,343.272195,tosse_antes_cirurgia
7,8,capacidade_vital_forcada,1,0.270288,0.265296,1.240907,344.096251,capacidade_vital_forcada
8,9,dor_antes_cirurgia,1,0.245797,0.259983,1.268849,345.337159,dor_antes_cirurgia
9,10,volume_expiratorio_forcado_1s,1,0.160590,0.095331,2.781962,346.606008,volume_expiratorio_forcado_1s
10,11,fraqueza_antes_cirurgia,1,0.105099,0.113391,2.506314,349.387970,fraqueza_antes_cirurgia

In [ ]:

resultado_final = ajustar_modelo(y, X_atual)

resultado_final.save(str(CAMINHO_MODELO_FINAL), remove_data=False)

print("Modelo final salvo em:")
print(CAMINHO_MODELO_FINAL)

print("\nResumo do modelo final:")
print(resultado_final.summary())

Modelo final salvo em:
outputs\modelo_final.pkl

Resumo do modelo final:
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:            obito_1_ano   No. Observations:                  470
Model:                            GLM   Df Residuals:                      457
Model Family:                Binomial   Df Model:                           12
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -175.95
Date:                Fri, 19 Jun 2026   Deviance:                       351.89
Time:                        09:11:28   Pearson chi2:                     437.
No. Iterations:                    20   Pseudo R-squ. (CS):            0.08881
Covariance Type:            nonrobust
=============================================================================================================================
                                                                coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------------------
constante                                                    -3.5903      0.543     -6.609      0.000      -4.655      -2.526
C(diagnostico, Treatment(reference='DGN3'))[T.DGN1]         -19.5674   2.92e+04     -0.001      0.999   -5.73e+04    5.73e+04
C(diagnostico, Treatment(reference='DGN3'))[T.DGN2]           0.4832      0.402      1.202      0.229      -0.305       1.271
C(diagnostico, Treatment(reference='DGN3'))[T.DGN4]           0.3239      0.456      0.710      0.478      -0.570       1.218
C(diagnostico, Treatment(reference='DGN3'))[T.DGN5]           2.0578      0.573      3.592      0.000       0.935       3.181
C(diagnostico, Treatment(reference='DGN3'))[T.DGN6]         -19.1338   1.44e+04     -0.001      0.999   -2.83e+04    2.82e+04
C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]           3.3996      1.508      2.254      0.024       0.444       6.355
C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12]     0.3815      0.318      1.200      0.230      -0.241       1.004
C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13]     1.2049      0.603      1.998      0.046       0.023       2.387
C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]     1.7591      0.589      2.987      0.003       0.605       2.913
dispneia_antes_cirurgia                                       1.1422      0.454      2.515      0.012       0.252       2.032
diabetes_mellitus_tipo_2                                      1.0287      0.429      2.398      0.016       0.188       1.870
tabagismo                                                     1.2102      0.489      2.477      0.013       0.253       2.168
=============================================================================================================================

In [ ]:

informacoes_finais = {
    "arquivo_base": str(BASE_PATH),
    "variavel_resposta": VAR_RESPOSTA,
    "alpha": ALPHA,
    "criterio_remocao": "Remover somente se p_valor_wald > alpha e p_valor_deviance > alpha",
    "n_observacoes": int(resultado_final.nobs),
    "n_eventos_obito": int(y.sum()),
    "n_nao_eventos": int((1 - y).sum()),
    "variaveis_modelo_final": X_atual.columns.tolist(),
    "variaveis_explicativas_modelo_final": [
        col for col in X_atual.columns if col not in ["const", "constante"]
    ],
    "blocos_finais": blocos_ativos,
    "colunas_constantes": colunas_constante,
    "n_parametros_modelo_final": int(len(resultado_final.params)),
    "deviance_modelo_final": float(resultado_final.deviance),
    "graus_liberdade_residuo": int(resultado_final.df_resid),
    "log_verossimilhanca": float(resultado_final.llf),
    "blocos_removidos": tabela_historico["bloco_removido"].tolist()
}

with open(CAMINHO_VARIAVEIS_FINAIS, "w", encoding="utf-8") as arquivo:
    json.dump(informacoes_finais, arquivo, ensure_ascii=False, indent=4)

print("Informações das variáveis finais salvas em:")
print(CAMINHO_VARIAVEIS_FINAIS)

Informações das variáveis finais salvas em:
outputs\variaveis_finais.json

In [ ]:

resumo_selecao = pd.DataFrame({
    "medida": [
        "n_variaveis_inicio",
        "n_variaveis_final",
        "n_blocos_inicio",
        "n_blocos_final",
        "n_blocos_removidos",
        "deviance_modelo_completo",
        "deviance_modelo_final",
        "log_verossimilhanca_modelo_final"
    ],
    "valor": [
        len(X.columns),
        len(X_atual.columns),
        len(blocos),
        len(blocos_ativos),
        len(tabela_historico),
        float(info_variaveis["deviance_modelo_completo"]),
        float(resultado_final.deviance),
        float(resultado_final.llf)
    ]
})

display(resumo_selecao)

print("Variáveis que permaneceram no modelo final:")
display(pd.DataFrame({"variavel_final": X_atual.columns}))

                             medida       valor
0                n_variaveis_inicio   25.000000
1                 n_variaveis_final   13.000000
2                   n_blocos_inicio   16.000000
3                    n_blocos_final    5.000000
4                n_blocos_removidos   11.000000
5          deviance_modelo_completo  341.187221
6             deviance_modelo_final  351.894284
7  log_verossimilhanca_modelo_final -175.947142

Variáveis que permaneceram no modelo final:

                                               variavel_final
0                                                   constante
1         C(diagnostico, Treatment(reference='DGN3'))[T.DGN1]
2         C(diagnostico, Treatment(reference='DGN3'))[T.DGN2]
3         C(diagnostico, Treatment(reference='DGN3'))[T.DGN4]
4         C(diagnostico, Treatment(reference='DGN3'))[T.DGN5]
5         C(diagnostico, Treatment(reference='DGN3'))[T.DGN6]
6         C(diagnostico, Treatment(reference='DGN3'))[T.DGN8]
7   C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC12]
8   C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC13]
9   C(tamanho_tumor_tnm, Treatment(reference='OC11'))[T.OC14]
10                                    dispneia_antes_cirurgia
11                                   diabetes_mellitus_tipo_2
12                                                  tabagismo